// <auto-generated />
using System;
using CLAIMS_Application.Part2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CLAIMS_Application.Part2.Migrations
{
    [DbContext(typeof(ClaimsContext))]
    [Migration("20251121193802_InitialCLaim")]
    partial class InitialCLaim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CLAIMS_Application.Part2.Models.MonthlyClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AdministratorReviewBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdministratorReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdministratorReviewNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdministratorStatus")
                        .HasColumnType("int");

                    b.Property<string>("CoordinatorReviewBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CoordinatorReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoordinatorReviewNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoordinatorStatus")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HRReviewBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HRReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HRReviewNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HRStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LecturerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MonthlyClaimsModels");
                });
#pragma warning restore 612, 618
        }
    }
}
